#ifndef KEYCODES_H_
#define KEYCODES_H_

#define KC_NO             0x00
#define KC_ROLL_OVER      0x01
#define KC_POST_FAIL      0x02
#define KC_UNDEFINED      0x03

#define KC_A              0x04
#define KC_B              0x05
#define KC_C              0x06
#define KC_D              0x07
#define KC_E              0x08
#define KC_F              0x09
#define KC_G              0x0A
#define KC_H              0x0B
#define KC_I              0x0C
#define KC_J              0x0D
#define KC_K              0x0E
#define KC_L              0x0F
#define KC_M              0x10
#define KC_N              0x11
#define KC_O              0x12
#define KC_P              0x13
#define KC_Q              0x14
#define KC_R              0x15
#define KC_S              0x16
#define KC_T              0x17
#define KC_U              0x18
#define KC_V              0x19
#define KC_W              0x1A
#define KC_X              0x1B
#define KC_Y              0x1C
#define KC_Z              0x1D

#define KC_ONE            0x1E
#define KC_TWO            0x1F
#define KC_THREE          0x20
#define KC_FOUR           0x21
#define KC_FIVE           0x22
#define KC_SIX            0x23
#define KC_SEVEN          0x24
#define KC_EIGHT          0x25
#define KC_NINE           0x26
#define KC_ZERO           0x27

#define KC_ENTER          0x28
#define KC_ESC            0x29
#define KC_BKSP           0x2A
#define KC_TAB            0x2B
#define KC_SPACE          0x2C
#define KC_MINUS          0x2D
#define KC_EQUAL          0x2E
#define KC_LSB            0x2F
#define KC_RSB            0x30
#define KC_BSLASH         0x31
#define KC_HASH           0x32
#define KC_SCOLON         0x33
#define KC_TICK           0x34
#define KC_BTK            0x35
#define KC_COMMA          0x36
#define KC_DOT            0x37
#define KC_FSLSH          0x38
#define KC_CAPS           0x39

#define KC_F1             0x3A
#define KC_F2             0x3B
#define KC_F3             0x3C
#define KC_F4             0x3D
#define KC_F5             0x3E
#define KC_F6             0x3F
#define KC_F7             0x40
#define KC_F8             0x41
#define KC_F9             0x42
#define KC_F10            0x43
#define KC_F11            0x44
#define KC_F12            0x45

#define KC_PSCREEN        0x46
#define KC_SCKLOCK        0x47
#define KC_PAUSE          0x48
#define KC_INSERT         0x49
#define KC_HOME           0x4A
#define KC_PGUP           0x4B
#define KC_DELETE         0x4C
#define KC_END            0x4D
#define KC_PGDOWN         0x4E
#define KC_RIGHT          0x4F
#define KC_LEFT           0x50
#define KC_DOWN           0x51
#define KC_UP             0x52
#define KC_NUMLK          0x53

#define KC_NSLSH          0x54
#define KC_NSTAR          0x55
#define KC_NINUS          0x56
#define KC_NPLUS          0x57
#define KC_NNTER          0x58
#define KC_N1             0x59
#define KC_N2             0x5A
#define KC_N3             0x5B
#define KC_N4             0x5C
#define KC_N5             0x5D
#define KC_N6             0x5E
#define KC_N7             0x5F
#define KC_N8             0x60
#define KC_N9             0x61
#define KC_N0             0x62
#define KC_NDOT           0x63
#define KC_NEQUAL         0x67
#define KC_NCOMMA         0x85
#define KC_NEQUAL_AS400   0x86

#define KC_BSLH           0x64

#define KC_APPLICATION    0x65
#define KC_POWER          0x66

#define KC_F13            0x68
#define KC_F14            0x69
#define KC_F15            0x6A
#define KC_F16            0x6B
#define KC_F17            0x6C
#define KC_F18            0x6D
#define KC_F19            0x6E
#define KC_F20            0x6F
#define KC_F21            0x70
#define KC_F22            0x71
#define KC_F23            0x72
#define KC_F24            0x73

#define KC_EXECUTE        0x74
#define KC_HELP           0x75
#define KC_MENU           0x76
#define KC_SELECT         0x77
#define KC_STOP           0x78
#define KC_AGAIN          0x79
#define KC_UNDO           0x7A
#define KC_CUT            0x7B
#define KC_COPY           0x7C
#define KC_PASTE          0x7D
#define KC_FIND           0x7E
#define KC__MUTE          0x7F
#define KC__VOLUP         0x80
#define KC__VOLDOWN       0x81
#define KC_CAPSLK_LEGACY  0x82
#define KC_NUMLK_LEGACY   0x83
#define KC_SCROLK_LEGACY  0x84
#define KC_INT1           0x87
#define KC_INT2           0x88
#define KC_INT3           0x89
#define KC_INT4           0x8A
#define KC_INT5           0x8B
#define KC_INT6           0x8C
#define KC_INT7           0x8D
#define KC_INT8           0x8E
#define KC_INT9           0x8F
#define KC_LANG1          0x90
#define KC_LANG2          0x91
#define KC_LANG3          0x92
#define KC_LANG4          0x93
#define KC_LANG5          0x94
#define KC_LANG6          0x95
#define KC_LANG7          0x96
#define KC_LANG8          0x97
#define KC_LANG9          0x98
#define KC_ALT_ERASE      0x99
#define KC_SYSREQ         0x9A
#define KC_CANCEL         0x9B
#define KC_CLEAR          0x9C
#define KC_PRIOR          0x9D
#define KC_RETURN         0x9E
#define KC_SEPARATOR      0x9F
#define KC_OUT            0xA0
#define KC_OPER           0xA1
#define KC_CLEAR_AGAIN    0xA2
#define KC_CRSEL          0xA3
#define KC_EXSEL          0xA4

#define KC_LCTRL          0xE0
#define KC_LSHFT          0xE1
#define KC_LALT           0xE2
#define KC_LOS            0xE3
#define KC_RCTRL          0xE4
#define KC_RSHFT          0xE5
#define KC_RALT           0xE6
#define KC_ROS            0xE7

#endif /* KEYCODES_H_ */